@startuml
title Following Author Subsequences
skinparam {
    ActorBackgroundColor #FFFFFF
    BoundaryBackgroundColor #FFFFFF
    ControlBackgroundColor #FFFFFF
    EntityBackgroundColor #FFFFFF
    DatabaseBackgroundColor #FFFFFF

    ActorBorderColor black
    BoundaryBorderColor black
    ControlBorderColor black
    EntityBorderColor black
    DatabaseBorderColor black
}

control UserService
control NotificationService
control EventEmitter
entity UserModel
database MongoDB

alt Already following (UNFOLLOW)
    UserService -> UserService: 1. Remove author from following_authors
    activate UserService
    UserService -> EventEmitter: 2. Emit follow_count_decrease
    activate EventEmitter
    UserService -> EventEmitter: 3. Emit follower_count_decrease
    deactivate EventEmitter
else Not following (FOLLOW)
    UserService -> UserModel: 4. Find follower username
    activate UserModel
    UserModel -> MongoDB: 5. findById authorId
    activate MongoDB
    MongoDB --> UserModel: 6. Follower data
    deactivate MongoDB
    UserModel --> UserService: 7. Follower data
    deactivate UserModel
    UserService -> UserModel: 8. Find author device_id
    activate UserModel
    UserModel -> MongoDB: 9. findById authorId
    activate MongoDB
    MongoDB --> UserModel: 10. Device id data
    deactivate MongoDB
    UserModel --> UserService: 11. Device id data
    deactivate UserModel

    UserService -> NotificationService: 12. Send follow notification
    activate NotificationService
    NotificationService --> UserService: 13. Send result
    deactivate NotificationService
    UserService -> UserService: 14. Remove failed device tokens
    activate UserService
    UserService -> EventEmitter: 15. Emit follow_count_increase
    deactivate UserService
    activate EventEmitter
    UserService -> EventEmitter: 16. Emit follower_count_increase
    deactivate EventEmitter
    deactivate UserService
end
@enduml
