@startuml
skinparam {
    ActorBackgroundColor #FFFFFF
    BoundaryBackgroundColor #FFFFFF
    ControlBackgroundColor #FFFFFF
    EntityBackgroundColor #FFFFFF
    DatabaseBackgroundColor #FFFFFF

    ActorBorderColor black
    BoundaryBorderColor black
    ControlBorderColor black
    EntityBorderColor black
    DatabaseBorderColor black
}

actor User
boundary "Profile Page (UI)" as UI
boundary Router
control UserController
control UserService
control JwtService
entity UserModel
database MongoDB

User -> UI: 1. Click Follow / Unfollow
activate User
activate UI

UI -> Router: 2. POST /toggle-follow
activate Router

Router -> UserController: 3. toggleFollowAuthor()
activate UserController
UserController -> UserService: 4. toggleFollowAuthor(token, authorId)

activate UserService
UserService -> JwtService: 5. Verify access token
activate JwtService
JwtService --> UserService: 6. Decoded user_id
deactivate JwtService

opt Decoide failed
    UserService --> UserController: 6.1. Return 401 Unauthorized
    UserController --> Router: 6.2. Return 401 Unauthorized
    Router --> UI: 6.3. HTTP response
    UI --> User: 6.4. Show error
end

UserService -> UserModel: 7. Find user by decoded.user_id
activate UserModel
UserModel -> MongoDB: 8. Get user
activate MongoDB
MongoDB --> UserModel: 9. User document
deactivate MongoDB
UserModel --> UserService: 10. User data
deactivate UserModel

opt User not found
    UserService -> UserController: 10.1. Return 401 Unauthorized
    UserController -> Router: 10.2. Return 401 Unauthorized
    Router -> UI: 10.3. HTTP response
    UI -> User: 10.4. Show error
end

ref over UserService, MongoDB
11. Following Author - Subsequences
end ref

UserService -> UserModel: 12. Save updated following_authors
activate UserModel
UserModel -> MongoDB: 13. Save user
activate MongoDB
MongoDB --> UserModel: 14. Saved
deactivate MongoDB
UserModel --> UserService: 15. Save result
deactivate UserModel

UserService --> UserController: 16. Return following & isFollowing
deactivate UserService

UserController --> Router: 17. HTTP response
deactivate UserController
Router --> UI: 18. Update follow button
deactivate Router
UI --> User: 19. Show follow state
deactivate UI
deactivate User
@enduml
