@startuml
skinparam {
    ActorBackgroundColor #FFFFFF
    BoundaryBackgroundColor #FFFFFF
    ControlBackgroundColor #FFFFFF
    EntityBackgroundColor #FFFFFF
    DatabaseBackgroundColor #FFFFFF

    ActorBorderColor black
    BoundaryBorderColor black
    ControlBorderColor black
    EntityBorderColor black
    DatabaseBorderColor black
}

actor User
boundary "Forgot Password UI" as UI
boundary Router
control AuthController
control AuthService
control UserService
control JwtService
control MailerService
entity UserModel
database MongoDB

User -> UI: 1. Submit forgot password (email)
activate User
activate UI

UI -> Router: 2. POST /auth/forgot-password
activate Router

Router -> AuthController: 3. call send email
activate AuthController

AuthController -> AuthService: 4. call send email
activate AuthService

opt Email invalid
    AuthService --> AuthController: 4.1. BadRequestException
    AuthController --> Router: 4.2. Return error
    Router --> UI: 4.3. Return error
    UI --> User: 4.4. Show error
end

ref over AuthService, UserService, UserModel, MongoDB
    5.  Subsequence - Find user for Password recovery
end ref

loop User not exist / banned / google / not verified
    AuthService --> AuthController: 5.1. BadRequestException
    AuthController --> Router: 5.2. Return error
    Router --> UI: 5.3. Return error
    UI --> User: 5.4. Show error
end

AuthService -> JwtService: 6. sign({email, action}, 15m)
activate JwtService
JwtService --> AuthService: 7. token
deactivate JwtService

AuthService -> MailerService: 8. send email
activate MailerService
MailerService --> AuthService: 9. mail sent
deactivate MailerService

opt Send mail failed
    AuthService --> AuthController: 9.1. InternalServerErrorException
    AuthController --> Router: 9.2. Return error
    Router --> UI: 9.3. Return error
    UI --> User: 9.4. Show error
end

ref over AuthService, UserService, UserModel, MongoDB
    10. Subsequence - Update verify code
end ref

opt Update failed
    AuthService --> AuthController: 10.1. InternalServerErrorException
    AuthController --> Router: 10.2. Return error
    Router --> UI: 10.3. Return error
    UI --> User: 10.4. Show error
end

AuthService --> AuthController: 11. Return success response
deactivate AuthService

AuthController --> Router: 12. Return HTTP response
deactivate AuthController
Router --> UI: 13. Show success message
deactivate Router
UI --> User: 14. Verification email sent
deactivate UI
deactivate User
@enduml
