@startuml
skinparam {
  ActorBackgroundColor #FFFFFF
  BoundaryBackgroundColor #FFFFFF
  ControlBackgroundColor #FFFFFF
  EntityBackgroundColor #FFFFFF
  DatabaseBackgroundColor #FFFFFF
  ActorBorderColor black
  BoundaryBorderColor black
  ControlBorderColor black
  EntityBorderColor black
  DatabaseBorderColor black
}

actor Admin
boundary "Admin Policy Form UI" as UI
boundary Router
control PoliciesController
control AccessTokenGuard
control RolesGuard
control PoliciesService
entity PoliciesModel
database MongoDB

Admin -> UI: 1. Fill form and submit
activate Admin
activate UI

UI -> Router: 2. POST /policies (status=Draft|Active)
activate Router

Router -> AccessTokenGuard: 3. canActivate(request)
activate AccessTokenGuard

opt Token invalid
  AccessTokenGuard --> Router: 3.1. Deny
  Router --> UI: 3.1.1. 401 Unauthorized
  UI --> Admin: 3.1.2. Show error message
end

AccessTokenGuard --> Router: 4. Allow
deactivate AccessTokenGuard

Router -> RolesGuard: 5. checkRole(ADMIN)
activate RolesGuard

opt Role invalid
  RolesGuard --> Router: 5.1. Deny
  Router --> UI: 5.2. 403 Forbidden
  UI --> Admin: 5.3. Show error message
end

RolesGuard --> Router: 6. Allow
deactivate RolesGuard

Router -> PoliciesController: 7. create(dto)
activate PoliciesController

PoliciesController -> PoliciesService: 8. create(body)
activate PoliciesService

opt slug is missing
  PoliciesService -> PoliciesService: 9. Generate slug
  activate PoliciesService
end
deactivate PoliciesService


PoliciesService -> PoliciesModel: 10. new(dto).save()
activate PoliciesModel

PoliciesModel -> MongoDB: 11. insert document
activate MongoDB
MongoDB --> PoliciesModel: 12. Saved document
deactivate MongoDB

PoliciesModel --> PoliciesService: 13. Created policy
deactivate PoliciesModel

opt Duplicate slug or DB error
  PoliciesService --> PoliciesController: 13.1. Throw error
  PoliciesController --> Router: 13.2. HTTP 400/500
  Router --> UI: 13.3. Create failed
  UI --> Admin: 13.4. Show error message
end

PoliciesService --> PoliciesController: 14. Created policy
deactivate PoliciesService

PoliciesController --> Router: 15. HTTP 201 response
deactivate PoliciesController

Router --> UI: 16. Return created policy
deactivate Router
UI --> Admin: 18. Create policy success
deactivate UI
deactivate Admin

@enduml