@startuml
skinparam {
    ActorBackgroundColor #FFFFFF
    BoundaryBackgroundColor #FFFFFF
    ControlBackgroundColor #FFFFFF
    EntityBackgroundColor #FFFFFF
    DatabaseBackgroundColor #FFFFFF

    ActorBorderColor black
    BoundaryBorderColor black
    ControlBorderColor black
    EntityBorderColor black
    DatabaseBorderColor black
}

actor User
boundary "Reset Password UI" as UI
boundary Router
control AuthController
control AuthService
control JwtService
control UserService
boundary HashUtil
entity UserModel
database MongoDB

User -> UI: 1. Submit new password + verification code
activate User
activate UI

UI -> Router: 2. POST /auth/verify-forgot-password
activate Router

Router -> AuthController: 3. verificationForgotPassword(code, password)
activate AuthController

AuthController -> AuthService: 4. verificationForgotPassword(token, password)
activate AuthService

opt Missing token
    AuthService --> AuthController: 4.1. BadRequestException
    AuthController --> Router: 4.2. Return error
    Router --> UI: 4.3. Return error
    UI --> User: 4.4. Show error
end

AuthService -> JwtService: 5. verify(token)
activate JwtService
opt Invalid / expired token
    JwtService --> AuthService: 5.1. Return error
    AuthService --> AuthController: 5.2. BadRequestException
    AuthController --> Router: 5.3. Return error
    Router --> UI: 5.4. Return error
    UI --> User: 5.5. Show error
end
JwtService --> AuthService: 6. payload
deactivate JwtService

opt Invalid payload
    AuthService --> AuthController: 6.1. BadRequestException
    AuthController --> Router: 6.2. BadRequestException
    Router --> UI: 6.3. Return error
    UI --> User: 6.4. Show error
end

ref over AuthService, UserService, UserModel, MongoDB
    7. Subsequence - Find user for Password Recovery
end ref

loop User invalid / banned / google / not verified / Verification code mismatch
    AuthService --> AuthController: 8.1. BadRequestException
    AuthController --> Router: 9.2. Return error
    Router --> UI: 9.3. Return error
    UI --> User: 9.4. Show error
end

ref over AuthService, UserService, HashUtil, UserModel, MongoDB
    10. Subsequence - Update new password
end ref

opt Update failed
    AuthService --> AuthController: 10.1. BadRequestException
    AuthController --> Router: 10.2. Return error
    Router --> UI: 10.3. Return error
    UI --> User: 10.4. Show error
end

AuthService --> AuthController: 11. success response
deactivate AuthService

AuthController --> Router: 12. HTTP response
deactivate AuthController
Router --> UI: 13. Show success message
deactivate Router
UI --> User: 14. Password updated successfully
deactivate UI
deactivate User
@enduml
